name: Memory Check
on: push
jobs:
  memcheck:
    name: memcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Valgrind dependency
        run: sudo apt-get install valgrind
      - name: Init CMake
        env:
          CC: gcc-9
          CXX: g++-9
        run: |
          mkdir -p ./build
          ./run_cmake_unix.sh
      - name: Build
        working-directory: build
        env:
          CC: gcc-9
          CXX: g++-9
        run: make all
      - name: check for leaks
        working-directory: build
        run: valgrind --tool=memcheck --leak-check=full --leak-resolution=med --show-leak-kinds=all --undef-value-errors=yes --track-origins=yes  --error-exitcode=1 --show-reachable=no ./src/RobotSquiggles_run
